import Head from "next/head";
import { Search } from "../components/Search";
import { useState } from "react";


function Home() {
  const [url, setUrl] = useState();

  return (
    <div>
      <Head>
        <title>Cubyts</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>
          Search for a website here
          <Search onSearch={setUrl} />
        </h1>
        {url && (
          <div className="flex flex-wrap justify-center w-3/4 h-screen">
            <iframe
              className="w-screen h-auto"
              title="Inline Frame Example"
              src={url}
            ></iframe>
          </div>
        )}
      </main>
    </div>
  );
}
export default Home;
