import Head from "next/head";
import { Search } from "../components/Search";
import { useState } from "react";
import { Capture } from "../components/Capture";

function Home() {
  const [url, setUrl] = useState();
  const [screenCapture, setScreenCapture] = useState();

  const handleCapture = (screen) => {
    setScreenCapture(screen);
  };
  return (
    <>
      <Head>
        <title>Design Collaborator</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Capture onEndCapture={handleCapture}>
        {({ onStartCapture }) => (
          <main className="h-screen p-4">
            <Search onSearch={setUrl} />
            {url && <button onClick={onStartCapture}>Capture</button>}
            {screenCapture && <img src={screenCapture} />}
            <div className="flex flex-wrap justify-center w-full p-4 h-full capture">
              {url && (
                <iframe
                  className="w-screen h-auto"
                  title="Inline Frame Example"
                  src={url}
                ></iframe>
              )}
            </div>
          </main>
        )}
      </Capture>
    </>
  );
}
export default Home;
